<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and judgehost-config.php

// Generated from 'judgehost-static.php.in' on Tue Feb 22 18:05:31 WET 2011.

define('DOMJUDGE_VERSION', '3.1.3');

define('BINDIR',      '/home/domjudge-run//domjudge/judgehost/bin');
define('ETCDIR',      '/home/domjudge-run//domjudge/judgehost/etc');
define('LIBDIR',      '/home/domjudge-run//domjudge/judgehost/lib');
define('LIBJUDGEDIR', '/home/domjudge-run//domjudge/judgehost/lib/judge');
define('LOGDIR',      '/home/domjudge-run//domjudge/judgehost/log');
define('TMPDIR',      '/home/domjudge-run//domjudge/judgehost/tmp');
define('JUDGEDIR',    '/home/domjudge-run//domjudge/judgehost/judgings');

define('RUNUSER',     'domjudge-run');
